site_name: FPGC6 Wiki

theme:
    name: material
    custom_dir: overrides

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - awesome-pages

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: False

repo_name: bartpleiter/FPGC6
repo_url: https://github.com/bartpleiter/fpgc6

site_url: https://www.b4rt.nl/fpgc

edit_uri: edit/master/Documentation/docs/

use_directory_urls: False
